import { faker } from '@faker-js/faker';
import * as repo from './data/repository.js';
import { emitNewWorkouts } from './socket.js';

let intervalId = null;

const generateFakeWorkout = () => {
  const type = faker.helpers.arrayElement(["Cardio", "Strength", "Flexibility", "Full Body"]);
  const adj = faker.word.adjective();
  const capitalizedAdj = adj.charAt(0).toUpperCase() + adj.slice(1);
  return {
    id: faker.string.uuid(),
    name: `${capitalizedAdj} ${type}`,
    type: type,
    duration: faker.number.int({ min: 15, max: 120 }),
    status: faker.helpers.arrayElement(['Planned', 'Completed']),
    exercises: [faker.helpers.arrayElement(['Squats', 'Running', 'Pushups', 'Plank'])],
    notes: 'Generated by Faker on Server',
    date: faker.date.recent().toISOString().split('T')[0]
  };
};

export const startSimulation = () => {
  if (intervalId) return false; // Already running

  console.log('Starting workout simulation loop...');
  intervalId = setInterval(async () => {
    const fakeWorkouts = [];
    const batchSize = faker.number.int({ min: 1, max: 3 }); // Add 1 to 3 items per tick
    
    for (let i = 0; i < batchSize; i++) {
      fakeWorkouts.push(generateFakeWorkout());
    }

    // Add to repository
    await repo.addWorkoutsBulk(fakeWorkouts);
    
    // Emit through WebSockets
    emitNewWorkouts(fakeWorkouts);
    
  }, 5000); // Every 5 seconds
  
  return true;
};

export const stopSimulation = () => {
  if (!intervalId) return false; // Not running

  console.log('Stopping workout simulation loop...');
  clearInterval(intervalId);
  intervalId = null;
  return true;
};

export const isSimulationRunning = () => {
  return intervalId !== null;
};
